import {questions} from './questions.js?v=3';
const app=document.querySelector('#app');let game=[],i=0,score=0,locked=false;const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const layout=x=>app.innerHTML=`<div class="shell"><header class="top"><div class="logo">Musk or Piker?</div><div class="tag">SOURCED. RANDOMIZED. FOLLOW THE POWER.</div></header>${x}<footer class="foot"><b>Every quote and fact links to its source.</b><span><a href="https://vote.gov/" target="_blank" rel="noopener">Register to vote or check your registration ↗</a><br>This site is independent and is not affiliated with any candidate, campaign, party or PAC.</span></footer></div>`;
function home(){layout(`<section class="stage hero"><div class="eyebrow">Who said it?</div><h1>MUSK<br>OR<br>PIKER?</h1><p>Two men say inflammatory things online. Only one owns the platform, holds billions in government contracts and spent nine figures shaping an election.</p><div class="context"><b>The point isn't that Piker is good.</b> It's that reach, money, ownership and state power change what a quote can do.</div><button class="start" id="start">Play 10 rounds →</button><p class="small">${questions.length} verified questions in the pool · updated periodically</p></section>`);document.querySelector('#start').onclick=start}
function start(){game=[...questions].sort(()=>Math.random()-.5).slice(0,10);i=score=0;show()}
function show(){locked=false;let q=game[i];layout(`<section class="stage"><div class="progress"><div class="bar" style="width:${i*10}%"></div></div><div class="round">ROUND ${i+1} / 10</div><blockquote class="quote">“${esc(q.quote)}”</blockquote><div class="choices"><button class="choice" data-a="musk"><span class="dot">E</span>Elon Musk</button><button class="choice" data-a="piker"><span class="dot">H</span>Hasan Piker</button></div></section>`);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(b.dataset.a))}
function answer(a){if(locked)return;locked=true;let q=game[i],ok=a===q.speaker;if(ok)score++;document.querySelector('.stage').innerHTML=`<div class="round">ROUND ${i+1} / 10</div><div class="answer ${ok?'correct':'wrong'}"><div class="eyebrow">${ok?'YOU GOT IT':'NOPE'}</div><h2>${q.speaker==='musk'?'ELON MUSK':'HASAN PIKER'}</h2><p class="fact">${esc(q.fact)}</p><div class="sources"><a href="${q.quoteSource}" target="_blank" rel="noopener">Verify the quote ↗</a><a href="${q.factSource}" target="_blank" rel="noopener">Source the fact ↗</a></div></div><button class="next">${i===9?'See my score':'Next quote'} →</button>`;document.querySelector('.next').onclick=()=>{i++;i<10?show():finish()}}
function finish(){let text=`I got ${score}/10 on Musk or Piker. The quotes are wild. The power behind them isn't equal. muskorpiker.com`;layout(`<section class="stage hero"><div class="eyebrow">Your score</div><div class="score">${score}/10</div><h2>${score>=8?'You know the feed. Do you know the power?':score>=5?'The blur is the point. The power is not.':'Reality has a branding problem.'}</h2><p>Hasan Piker has an audience. Elon Musk has an audience, a platform, at least $38 billion in government support for his companies, and more than $291 million in 2024 Republican political giving.</p><button class="share" id="share">Share score</button><button class="again" id="again">Play another round</button><p id="msg"></p></section>`);document.querySelector('#again').onclick=start;document.querySelector('#share').onclick=async()=>{try{if(navigator.share)await navigator.share({title:'Musk or Piker?',text,url:'https://muskorpiker.com'});else{await navigator.clipboard.writeText(text);document.querySelector('#msg').textContent='Score copied.'}}catch{}}}
home();
