import {questions} from './questions.js?v=3';
const app=document.querySelector('#app');let game=[],i=0,score=0,locked=false;const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const layout=x=>app.innerHTML=`<div class="shell"><header class="top"><div class="logo">Musk or Piker?</div><div class="tag">SOURCED. RANDOMIZED. FOLLOW THE POWER.</div></header>${x}<footer class="foot"><b>Every quote and fact links to its source.</b><span><a href="mailto:corrections@muskorpiker.com?subject=Musk%20or%20Piker%20correction">Report a correction ↗</a><br><a href="https://vote.gov/" target="_blank" rel="noopener">Register to vote or check your registration ↗</a><br>This site is independent and is not affiliated with any candidate, campaign, party or PAC.</span></footer></div>`;
const encodedGame=()=>game.map(q=>questions.indexOf(q)).join('-');
const challengeUrl=()=>`${location.origin}${location.pathname}?rounds=${encodedGame()}`;
function seededGame(){const raw=new URLSearchParams(location.search).get('rounds');if(!raw)return null;const ids=raw.split('-').map(Number);return ids.length===10&&new Set(ids).size===10&&ids.every(n=>Number.isInteger(n)&&questions[n])?ids.map(n=>questions[n]):null}
function home(){const seeded=seededGame();layout(`<section class="stage hero"><div class="eyebrow">Who said it?</div><h1>MUSK<br>OR<br>PIKER?</h1><button class="start" id="start">${seeded?'Play this 10-round challenge':'Play 10 rounds'} →</button><p class="small">${questions.length} verified questions in the pool · updated periodically</p></section>`);document.querySelector('#start').onclick=()=>start(seeded)}
function start(seed=null){game=seed||[...questions].sort(()=>Math.random()-.5).slice(0,10);i=score=0;show()}
function show(){locked=false;let q=game[i];layout(`<section class="stage"><div class="progress"><div class="bar" style="width:${i*10}%"></div></div><div class="round">ROUND ${i+1} / 10</div><blockquote class="quote">“${esc(q.quote)}”</blockquote><div class="choices"><button class="choice" data-a="musk"><span class="dot">E</span>Elon Musk</button><button class="choice" data-a="piker"><span class="dot">H</span>Hasan Piker</button></div></section>`);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(b.dataset.a))}
function answer(a){if(locked)return;locked=true;let q=game[i],ok=a===q.speaker;if(ok)score++;document.querySelector('.stage').innerHTML=`<div class="round">ROUND ${i+1} / 10</div><div class="answer ${ok?'correct':'wrong'}"><div class="eyebrow">${ok?'YOU GOT IT':'NOPE'}</div><h2>${q.speaker==='musk'?'ELON MUSK':'HASAN PIKER'}</h2><p class="fact">${esc(q.fact)}</p><div class="sources"><a href="${q.quoteSource}" target="_blank" rel="noopener">Verify the quote ↗</a><a href="${q.factSource}" target="_blank" rel="noopener">Source the fact ↗</a></div></div><button class="next">${i===9?'See my score':'Next quote'} →</button>`;document.querySelector('.next').onclick=()=>{i++;i<10?show():finish()}}
function scoreCard(){const c=document.createElement('canvas');c.width=1200;c.height=630;const x=c.getContext('2d');x.fillStyle='#f4f0e7';x.fillRect(0,0,c.width,c.height);x.fillStyle='#ff4f6d';x.fillRect(0,0,28,c.height);x.fillStyle='#111';x.font='800 34px Inter, Arial';x.fillText('MUSK OR PIKER?',75,85);x.font='900 230px Arial Black, Arial';x.fillText(`${score}/10`,70,350);x.font='800 45px Inter, Arial';x.fillText(score>=8?'You know the feed. Do you know the power?':score>=5?'The blur is the point. The power is not.':'Reality has a branding problem.',75,445);x.font='600 28px Inter, Arial';x.fillText('Take the same 10-round challenge',75,515);x.fillText('muskorpiker.com',75,560);return c}
async function shareScore(){const url=challengeUrl(),text=`I got ${score}/10 on Musk or Piker. Take the same 10-round challenge:`;const blob=await new Promise(r=>scoreCard().toBlob(r,'image/png'));const file=new File([blob],`musk-or-piker-${score}-of-10.png`,{type:'image/png'});try{if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:'Musk or Piker?',text,url,files:[file]});else if(navigator.share)await navigator.share({title:'Musk or Piker?',text,url});else{await navigator.clipboard.writeText(`${text} ${url}`);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();document.querySelector('#msg').textContent='Challenge link copied and score card downloaded.'}}catch{}}
function finish(){layout(`<section class="stage hero"><div class="eyebrow">Your score</div><div class="score">${score}/10</div><h2>${score>=8?'You know the feed. Do you know the power?':score>=5?'The blur is the point. The power is not.':'Reality has a branding problem.'}</h2><p>Hasan Piker has an audience. Elon Musk has an audience, a platform, at least $38 billion in government support for his companies, and more than $291 million in 2024 Republican political giving.</p><button class="share" id="share">Share score card</button><button class="share" id="challenge">Copy same 10-round challenge</button><button class="again" id="again">Play another round</button><p id="msg"></p></section>`);document.querySelector('#again').onclick=()=>{history.replaceState(null,'',location.pathname);start()};document.querySelector('#share').onclick=shareScore;document.querySelector('#challenge').onclick=async()=>{await navigator.clipboard.writeText(challengeUrl());document.querySelector('#msg').textContent='Same 10-round challenge link copied.'}}
home();
